language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - npm install -g bower
  - bower install
  - npm install -g gulp
script: 
  - gulp build
  - gulp deploy