language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - chmod a+x ./prebuild.sh
  - ./prebuild.sh
  - npm install -g bower
  - bower install
  - npm install -g gulp
script: 
  - gulp build
  - gulp deploy